### ISSUE TITLE
Performance of loading models and prediction

### ISSUE THREAD

**Issue by uellue** [MichaelO1993/PACBED-CNN#6]
Currently, loading a model and performing a prediction takes a long time, order of magnitude 30 s on CPU.

We should look into ways to make it faster.

- [ ] Get GPU to work on Moellenstedt
- [x] Work at lower resolution -- currently almost 4k x 4k!
- [x] Work in "grey scale" resp. numerical values.

For a prototype, 5 s for a prediction incl. loading would be desirable.

**Comment by MichaelO1993** [comment]
Time could be reduced from around 30 s to 6 s.

In the folder tensorflow_lite are the optimized prediction and training, which takes for:
- Loading: ~0.2 s
- Prediction: ~3.2 s (depends strongly on how often the scaling is run)
- Validation: ~2.4 s

Using GPU did not speed up the prediction-script! (Total time with GPU 5.9 s and with CPU 5.8 s)

Performance is increased by:
- Downscaling measured PACBED immediately after loading to 4x the CNN input
- Converting PACBED to grayscale and converting to RGB only for predictions by CNNs (CNNs trained for RGB)
- Using tensorflow-lite saved models to speed up loading. (CNN-Training is updated to save correct files)
- Removing unnecessary operations at validation

**Comment by uellue** [comment]
Thanks a lot, this should be in the ballpark for the prototype. :-)
